{{- if eq (.Values.services.trino.enabled | toString | lower) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-trino-config
  namespace: {{ .Release.Namespace }}
data:
  TRINO_ROLE: coordinator
  DISCOVERY_URI: http://{{ .Release.Name }}-trino-svc
{{- end }}