{{- if eq .Values.services.docs.enabled "true" }}

apiVersion: v1
data:
  AWS_APP_BUCKET_NAME: fyno-app
  FYNODOCSQ_PREFIX: '{fynoq:fdsq}'
  LOG_CONSOLE_ENABLE: "true"
  LOG_LEVEL: debug
  # MINIO credentials are now sourced from secret
  MINIO_ENDPOINT: {{ if .Values.domains.ssl }}https{{ else }}http{{ end }}://{{ .Values.domains.media }}
  DOCS_URL: http://{{ .Release.Name }}-pdfservice-svc.{{ .Release.Namespace }}.svc.cluster.local:80
  NODE_ENV: prod
  QUEUE_NAME: fynodocsq
  LOG_LEVEL: "info"
  LOG_CONSOLE_ENABLE: "true"
  AWS_REGION: "ap-south-1"
  # REDIS connection details are now sourced from secret
  # REDIS_QUEUE connection details are now sourced from secret
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fynodocs-service-config
  namespace: {{ .Release.Namespace }}

{{- end }}