{{- if eq (.Values.services.trino_worker.enabled | toString | lower) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-trino-worker-config
  namespace: {{ .Release.Namespace }}
data:
  TRINO_ROLE: worker
  DISCOVERY_URI: http://{{ .Release.Name }}-trino-svc
{{- end }}