{{- if eq .Values.services.RedisController.enabled "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-db-ha-scripts
  namespace: {{ .Release.Namespace }}
data:
  redis_ha_controller.py: {{ .Files.Get "files/redis_ha_controller.py" | quote }}
{{- end }}
