{{- if eq .Values.services.RedisDB.enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redis-password: {{ .Values.secrets.redisPassword | b64enc }}
{{- end }}
