apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: fyno
    meta.helm.sh/release-namespace: fyno
  creationTimestamp: "2025-12-26T11:29:17Z"
  generation: 7
  labels:
    app.kubernetes.io/managed-by: Helm
  name: fyno-gateway
  namespace: istio-system
  resourceVersion: "46569546"
  uid: 822b8856-352b-4bd6-a5a1-8ae19389d2ce
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - eks-api.dev.fyno.io
    - eks-app-api.dev.fyno.io
    - eks-loki.dev.fyno.io
    - eks-app.dev.fyno.io
    - eks-callback.dev.fyno.io
    - eks-prometheus.dev.fyno.io
    - eks-inapp.dev.fyno.io
    - eks-monitor.dev.fyno.io
    - eks-fy1.dev.fyno.io
    - eks-grafana.dev.fyno.io
    - eks-media.dev.fyno.io
    - eks-dev-thelistmanager.dev.fyno.io
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - mongo-node1.dev.fyno.io
    - mongo-node2.dev.fyno.io
    port:
      number: 443
      protocol: TCP
      name: mongo
