{{- if eq .Values.services.RedisController.enabled "true" }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis-logstream.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-logstream.labels" . | nindent 4 }}
{{- end }}
{{- end }}
