{{- if eq (.Values.services.trino_worker.enabled | toString | lower) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-trino-worker-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
{{- end }}