{{- if eq (.Values.services.pdfservice.enabled | toString | lower) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pdfservice-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
{{- end }}