{{- if eq .Values.services.monitor.enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-monitor-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_HOST: {{ .Values.db.REDIS_QUEUE_HOST | b64enc }}
  REDIS_PORT: {{ .Values.db.REDIS_QUEUE_PORT | b64enc }}
  REDIS_PASSWORD: {{ .Values.db.REDIS_QUEUE_PASSWORD | b64enc }}
{{- end }}
