{{- if eq .Values.services.analytics.enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-analytics-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.db.MARIA_DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.db.MARIA_DB_PASSWORD | b64enc }}
  DB_PORT: {{ .Values.db.MARIA_DB_PORT | b64enc }}
  DB_HOST: {{ .Values.db.MARIA_DB_HOST | b64enc }}
  MONGO_DB_USER: {{ .Values.db.MONGO_DB_USER | b64enc }}
  MONGO_DB_PASSWORD: {{ .Values.db.MONGO_DB_PASSWORD | b64enc }}
  MONGO_DB_HOST: {{ .Values.db.MONGO_DB_HOST | b64enc }}
  MONGO_DB_PORT: {{ .Values.db.MONGO_DB_PORT | b64enc }}
  AUTOMATION_LOGS_READ_FROM: {{ (printf "mongodb://%s:%s@%s:%s/fyno_app.automationlogs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  AUTOMATION_LOGS_WRITE_TO: {{ (printf "mongodb://%s:%s@%s:%s/fyno_analytics_v2.summary_automation_logs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  DLR_LOGS_READ_FROM: {{ (printf "mongodb://%s:%s@%s:%s/fyno_app.deliverylogs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  DLR_LOGS_WRITE_TO: {{ (printf "mongodb://%s:%s@%s:%s/fyno_analytics_v2.summary_dlr_logs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  EVENT_LOGS_READ_FROM: {{ (printf "mongodb://%s:%s@%s:%s/fyno_app.eventslogs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  EVENT_LOGS_WRITE_TO: {{ (printf "mongodb://%s:%s@%s:%s/fyno_analytics_v2.summary_event_logs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  SENT_LOGS_READ_FROM: {{ (printf "mongodb://%s:%s@%s:%s/fyno_app.logs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  SENT_LOGS_WRITE_TO: {{ (printf "mongodb://%s:%s@%s:%s/fyno_analytics_v2.summary_sent_logs?authSource=admin" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT) | b64enc }}
  REDIS_USER: {{ .Values.db.REDIS_CACHE_USER | b64enc }}
  REDIS_PASSWORD: {{ .Values.db.REDIS_CACHE_PASSWORD | b64enc }}
  REDIS_HOST: {{ .Values.db.REDIS_CACHE_HOST | b64enc }}
  REDIS_PORT: {{ .Values.db.REDIS_CACHE_PORT | b64enc }}
{{- end }}
