{{- if or
  (eq .Values.services.api_service.enabled "true")
  (eq .Values.services.apiservice.enabled "true")
  (eq .Values.services.automationservice.enabled "true")
  (eq .Values.services.backend.enabled "true")
  (eq .Values.services.callback.enabled "true")
  (eq .Values.services.dlr.enabled "true")
  (eq .Values.services.eventservice.enabled "true")
  (eq .Values.services.log.enabled "true")
  (eq .Values.services.transporter.enabled "true")
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_CLUSTER: {{ .Values.db.REDIS_CACHE_CLUSTER | b64enc }}
  REDIS_HOST: {{ .Values.db.REDIS_CACHE_HOST | b64enc }}
  REDIS_PASSWORD: {{ .Values.db.REDIS_CACHE_PASSWORD | b64enc }}
  REDIS_USER: {{ .Values.db.REDIS_CACHE_USER | b64enc }}
  REDIS_PORT: {{ .Values.db.REDIS_CACHE_PORT | b64enc }}
  REDIS_QUEUE_HOST: {{ .Values.db.REDIS_QUEUE_HOST | b64enc }}
  REDIS_QUEUE_USER: {{ .Values.db.REDIS_QUEUE_USER | b64enc }}
  REDIS_QUEUE_PASSWORD: {{ .Values.db.REDIS_QUEUE_PASSWORD | b64enc }}
  REDIS_QUEUE_PORT: {{ .Values.db.REDIS_QUEUE_PORT | b64enc }}
  CAMPAIGN_REDIS_QUEUE_HOST: {{ .Values.db.REDIS_QUEUE_HOST | b64enc }}
  CAMPAIGN_REDIS_QUEUE_PASSWORD: {{ .Values.db.REDIS_QUEUE_PASSWORD | b64enc }}
  CAMPAIGN_REDIS_QUEUE_PORT: {{ .Values.db.REDIS_QUEUE_PORT | b64enc }}
  MDB_REDIS_HOST: {{ .Values.db.REDIS_DB_HOST | b64enc }}
  MDB_REDIS_USER: {{ .Values.db.REDIS_DB_USER | b64enc }}
  MDB_REDIS_PASSWORD: {{ .Values.db.REDIS_DB_PASSWORD | b64enc }}
  MDB_REDIS_PORT: {{ .Values.db.REDIS_DB_PORT | b64enc }}
  MINIO_ACCESS_KEY_ID: {{ .Values.db.MINIO_USER | b64enc }}
  MINIO_SECRET_ACCESS_KEY: {{ .Values.db.MINIO_PASSWORD | b64enc }}
  DB_HOST: {{ .Values.db.MARIA_DB_HOST | b64enc }}
  DB_PASSWORD: {{ .Values.db.MARIA_DB_PASSWORD | b64enc }}
  DB_PORT: {{ .Values.db.MARIA_DB_PORT | b64enc }}
  DB_USER: {{ .Values.db.MARIA_DB_USER | b64enc }}
  
{{- end }}
