{{- if eq .Values.services.docs.enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-fynodocs-service-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.db.MARIA_DB_USER | b64enc }}
  MINIO_ACCESS_KEY_ID: {{ .Values.db.MINIO_USER | b64enc }}
  MINIO_SECRET_ACCESS_KEY: {{ .Values.db.MINIO_PASSWORD | b64enc }}
  DB_PASSWORD: {{ .Values.db.MARIA_DB_PASSWORD | b64enc }}
  DB_PORT: {{ .Values.db.MARIA_DB_PORT | b64enc }}
  DB_HOST: {{ .Values.db.MARIA_DB_HOST | b64enc }}
  MONGO_DB_USER: {{ .Values.db.MONGO_DB_USER | b64enc }}
  MONGO_DB_PASSWORD: {{ .Values.db.MONGO_DB_PASSWORD | b64enc }}
  MONGO_DB_HOST: {{ .Values.db.MONGO_DB_HOST | b64enc }}
  MONGO_DB_PORT: {{ .Values.db.MONGO_DB_PORT | b64enc }}
  MONGODB_URL: {{ printf "mongodb://%s:%s@%s:%s" .Values.db.MONGO_DB_USER .Values.db.MONGO_DB_PASSWORD .Values.db.MONGO_DB_HOST .Values.db.MONGO_DB_PORT | b64enc }}
  REDIS_USER: {{ .Values.db.REDIS_CACHE_USER | b64enc }}
  REDIS_PASSWORD: {{ .Values.db.REDIS_CACHE_PASSWORD | b64enc }}
  REDIS_HOST: {{ .Values.db.REDIS_CACHE_HOST | b64enc }}
  REDIS_PORT: {{ .Values.db.REDIS_CACHE_PORT | b64enc }}
  REDIS_QUEUE_HOST: {{ .Values.db.REDIS_QUEUE_HOST | b64enc }}
  REDIS_QUEUE_PORT: {{ .Values.db.REDIS_QUEUE_PORT | b64enc }}
  REDIS_QUEUE_PASSWORD: {{ .Values.db.REDIS_QUEUE_PASSWORD | b64enc }}
{{- end }}
