{{- if eq .Values.services.license.enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-license-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_HOST: {{ .Values.db.REDIS_DB_HOST | toString | b64enc }}
  REDIS_PORT: {{ .Values.db.REDIS_DB_PORT | toString | b64enc }}
  REDIS_PASSWORD: {{ .Values.db.REDIS_DB_PASSWORD | toString | b64enc }}
{{- end }}
