{{- if eq .Values.services.frontend.enabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-service-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TEMP: {{ "test" | b64enc }}
{{- end }}
